dependencies:
- name: spinnaker
  version: 1.23.0
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: redis.enabled
- name: prometheus-operator
  version: 8.3.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: kibana
  version: 7.8.1
  repository: https://helm.elastic.co
- name: elasticsearch
  version: 7.8.1
  repository: https://helm.elastic.co
- name: prometheus-blackbox-exporter
  version: 1.5.1
  repository: https://kubernetes-charts.storage.googleapis.com
